version: "3.8"
services:
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend/app:/usr/src/app
  #   ports:
  #     - 3000:3000
  #   working_dir: "/usr/src/app"
  #   command: sh -c "npm run start"
  backend:
    build: ./backend
    depends_on:
      - db
    working_dir: "/var/www/html"
    volumes:
      - ./backend/app:/var/www/html
      - ./backend/php.ini:/usr/local/etc/php/php.ini
      - ./backend/php.ini:/usr/local/etc/php/php.ini-development
      - ./backend/php.ini:/usr/local/etc/php/php.ini-production
  web:
    build: ./server
    ports:
      - 8000:80
    depends_on:
      - backend
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
volumes:
  db:
